workflows: compliance: Modernize and update
Align to the upstream counterpart, adopting all the improvements and
modernizing the workflow.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

diff --git a/.github/workflows/compliance.yml b/.github/workflows/compliance.yml
--- a/.github/workflows/compliance.yml
+++ b/.github/workflows/compliance.yml
@@ -7,15 +7,19 @@ jobs:
     runs-on: ubuntu-latest
     name: Run compliance checks on patch series (PR)
     steps:
+    - name: Update PATH for west
+      run: |
+        echo "$HOME/.local/bin" >> $GITHUB_PATH
+
     - name: Checkout the code
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
       with:
         path: ncs/nrf
         ref: ${{ github.event.pull_request.head.sha }}
         fetch-depth: 0
 
     - name: cache-pip
-      uses: actions/cache@v1
+      uses: actions/cache@v3
       with:
         path: ~/.cache/pip
         key: ${{ runner.os }}-doc-pip
@@ -24,10 +28,9 @@ jobs:
       working-directory: ncs/nrf
       run: |
         pip3 install -U pip
-        pip3 install  -U setuptools
-        export PATH="$HOME/.local/bin:$PATH"
-        pip3 install  -U wheel
-        grep -E "python-magic|junitparser|gitlint|pylint|pykwalify" scripts/requirements-fixed.txt | xargs pip3 install -U
+        pip3 install -U setuptools
+        pip3 install -U wheel
+        grep -E "python-magic|junitparser|lxml|gitlint|pylint|pykwalify" scripts/requirements-fixed.txt | xargs pip3 install -U
         grep -E "west" scripts/requirements-fixed.txt | xargs pip3 install -U
         pip3 show -f west
 
@@ -36,11 +39,13 @@ jobs:
         BASE_REF: ${{ github.base_ref }}
       working-directory: ncs/nrf
       run: |
-        export PATH="$HOME/.local/bin:$PATH"
-        export PATH="$HOME/bin:$PATH"
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         git remote -v
+        # Ensure there's no merge commits in the PR
+        [[ "$(git rev-list --merges --count origin/${BASE_REF}..)" == "0" ]] || \
+        (echo "::error ::Merge commits not allowed, rebase instead";false)
+
         git rebase origin/${BASE_REF}
         # debug
         git log  --pretty=oneline | head -n 10
@@ -56,16 +61,16 @@ jobs:
       working-directory: ncs/nrf
       if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
       run: |
-        export PATH="$HOME/.local/bin:$PATH"
-        export PATH="$HOME/bin:$PATH"
         export ZEPHYR_BASE="$(dirname "$(pwd)")/zephyr"
         # debug
         ls -la
         git log --pretty=oneline | head -n 10
-        $ZEPHYR_BASE/scripts/ci/check_compliance.py -m Codeowners -m Devicetree -m Gitlint -m Identity -m Nits -m pylint -m checkpatch -m KconfigBasic -c origin/${BASE_REF}..
+        # For now we run KconfigBasic, but we should transition to Kconfig
+        $ZEPHYR_BASE/scripts/ci/check_compliance.py --annotate -e Kconfig \
+        -c origin/${BASE_REF}..
 
     - name: upload-results
-      uses: actions/upload-artifact@v2
+      uses: actions/upload-artifact@v3
       continue-on-error: True
       if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
       with:
@@ -76,24 +81,24 @@ jobs:
       working-directory: ncs/nrf
       if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
       run: |
+        export ZEPHYR_BASE="$(dirname "$(pwd)")/zephyr"
         if [[ ! -s "compliance.xml" ]]; then
           exit 1;
         fi
 
-    - name: check-warns
-      working-directory: ncs/nrf
-      run: |
-        for file in Nits.txt checkpatch.txt Identity.txt Gitlint.txt pylint.txt Devicetree.txt Kconfig.txt KconfigBasic.txt Codeowners.txt; do
-          if [[ -s $file ]]; then
-             errors=$(cat $file)
-             errors="${errors//'%'/'%25'}"
-             errors="${errors//$'\n'/'%0A'}"
-             errors="${errors//$'\r'/'%0D'}"
-             echo "::error file=${file}::$errors"
-             exit=1
+        files=($($ZEPHYR_BASE/scripts/ci/check_compliance.py -l))
+        for file in "${files[@]}"; do
+          f="${file}.txt"
+          if [[ -s $f ]]; then
+            errors=$(cat $f)
+            errors="${errors//'%'/'%25'}"
+            errors="${errors//$'\n'/'%0A'}"
+            errors="${errors//$'\r'/'%0D'}"
+            echo "::error file=${f}::$errors"
+            exit=1
           fi
         done
 
-        if [[ $exit == 1 ]]; then
-          exit 1
+        if [ "${exit}" == "1" ]; then
+          exit 1;
         fi
